### ISSUE TITLE
./setup.sh failed

### ISSUE THREAD

**Issue by mcepl** [waartaa/waartaa#120]
On RHEL-7 I get this in the end of run of setup.sh:

```
./setup.sh: line 13: cd: waartaa: No such file or directory

Done installing smart packages
cp: cannot stat ‘server/settings-local.js-dist’: No such file or directory
```

Only settings-local.js-dist I have is in `./app/server/settings-local.js-dist`

Isn’t `s/wartaa/app/g` in order?

**Comment by rtnpro** [comment]
Hey @mcepl,

Thanks for reporting this issue. We have fixed the `setup.sh` script. Please give it a shot.

Regards,
rtnpro
