### ISSUE TITLE
Implement single bookmarking feature in live chat page and search page

### ISSUE THREAD

**Issue by D-Ne0** [waartaa/waartaa#126]
This will give user option to bookmark a chat message in chat page. There will be empty star icon before message on hover to bookmark it. Any previous message bookmarked will be show using a filled star icon.

@sayanchowdhury, @rtnpro: Please have a look at model schema

```
Bookmarks {
  label: String,
  channel_log_ids: List<String>,
  user: String,
  user_id: String
}
```

**Comment by rtnpro** [comment]
```
Bookmarks {
  label: String,
  roomType: String ('channel'/'pm'/'server'),
  logIds: List<String>,
  user: String,
  userId: String,
  created: Datetime,
  lastUpdated: Datetime,
  creator: String,
  creatorId: String
}
```

Let's follow camelCase way of writing variable names.

@sayanchowdhury @D-Ne0 , I think this will cover all cases now and in the future as well. What do you say?

**Comment by D-Ne0** [comment]
@rtnpro what is the difference between user and creator? In my schema 'user' is the one who creates bookmark.

**Comment by rtnpro** [comment]
What if me as admin would like to create a bookmark for another user? In
this case, the admin is the creator, and the user is the user for whom the
bookmark was created.

On Wed, Jul 2, 2014 at 1:19 AM, Lalit Khattar notifications@github.com
wrote:

> @rtnpro https://github.com/rtnpro what is the difference between user
> and creator? In my schema 'user' is the one who creates bookmark.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/waartaa/waartaa/issues/126#issuecomment-47701842.

## 

Ratnadeep Debnath,
https://www.waartaa.com
GPG Fingerprint: 033C 8041 A0E9 CDBA 2E02  B785 2119 5486 F245 DFD6

**Comment by D-Ne0** [comment]
PR: https://github.com/waartaa/waartaa/pull/129/
