### ISSUE TITLE
Network can not be closed

### ISSUE THREAD

**Issue by RobertEcker** [waartaa/waartaa#127]
Network (see screenshot) can not be closed although i click on the close button.
I use FF 30.

![freenodecantbeclosed](https://cloud.githubusercontent.com/assets/6156052/3484998/673ebcbe-03be-11e4-91b0-d8a2d550b8fc.jpg)

**Comment by rtnpro** [comment]
Hi @RobertEcker ,

Thanks for reporting this issue. I will check it out and get back to you ASAP.

Regards,
rtnpro
