### ISSUE TITLE
Connection to server fails.

### ISSUE THREAD

**Issue by darkowlzz** [waartaa/waartaa#13]
On submitting server name, nick and channel name, there seems to be continuous attempts to connect which fails with the following errors in paste.

https://pastebin.mozilla.org/3860338

**Comment by abhishekvp** [comment]
I think this issue has been resolved, but forgotten to be closed. I just tried and got connected to the mozilla server and the requested channels.

**Comment by rtnpro** [comment]
@abhishekvp Thanks for the update. I forgot to close this issue.

**Comment by swarnava** [comment]
reproducible from my side
