### ISSUE TITLE
Connect to IRC over SSL?

### ISSUE THREAD

**Issue by cjb** [waartaa/waartaa#130]
Hi, is there a way to tell Waartaa to connect to freenode/oftc on their SSL ports, instead of connecting unencrypted?  Thanks.

**Comment by rtnpro** [comment]
Hey @cjb 

Thanks for trying out Waartaa! Please add the certificate files as mentioned in https://github.com/waartaa/waartaa/tree/master/app/private/certs in `app/private/certs` directory, and waartaa will start connecting the secure `6697` port of the IRC servers (Freenode/Mozilla).

**Comment by rtnpro** [comment]
@cjb Did the above comment help? Let me know if there's any issue :)

**Comment by cjb** [comment]
@rtnpro Thanks a lot!  It works for Freenode and Mozilla, but fails for OFTC.  Any ideas?

**Comment by rtnpro** [comment]
@cjb Yes, I see. I can reproduce the failure to connect to OFTC over SSL. node-irc is getting connection 'close' events from the OFTC server. I am trying to debug and resolve this issue. I will update you on my progress on this issue.

**Comment by rtnpro** [comment]
@cjb 

I've just pushed a fix for this issue to master. Please sync your `app/server/settings-local.js` with https://github.com/waartaa/waartaa/blob/master/app/server/settings-local.js-dist:
- `GlobalServers.oftc.ssl`
- `SSL*` keys in `CONFIG`

And restart your server. You should be able to connect OFTC IRC server now over SSL. Please let me know if there's any issue :)

**Comment by cjb** [comment]
@rtnpro It works great, thank you very much!

Just wanted to note that I think the change that adds the `SSL*` keys silently downgrades the connection for existing Waartaa users from SSL to no-SSL (without the new config options it no longer uses SSL when the keys are present), which might be surprising to users.

**Comment by rtnpro** [comment]
@cjb 

It's a valid point that failure to add `SSL*` keys in settings file will silently lead to non SSL connection to IRC for existing Waartaa users. I will push a fix to have a sane fallback to using pre existing SSL credential files.

Thanks for pointing it out :+1:
