### ISSUE TITLE
Finalize tasklist for admin interface

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#131]
My suggestions:
- Monitor active node-irc clients. I should be able to see all active node-irc clients running in the app along with their connection status, and I should be able to connect, disconnect them.
- Analytics for channel/server logs arriving per second and channel/server logs written to db per second
- Analytics for active users on website, user signup and signin
- Allow access to collections data like django. There are some admin packages for meteor.

@sayanchowdhury @D-Ne0 please comment.

**Comment by D-Ne0** [comment]
@rtnpro @sayanchowdhury Checkout django like admin package for meteor: https://github.com/gterrono/houston

Let me know if I can use it.

**Comment by rtnpro** [comment]
I don't like houston

**Comment by rtnpro** [comment]
Initial mockup for admin dashboard:
![admin_dashboard](https://cloud.githubusercontent.com/assets/231684/3623052/62830d9c-0e45-11e4-9d9b-6c66c1abab93.png)

https://gist.github.com/rtnpro/8c80b8010f402c02d36e

**Comment by rtnpro** [comment]
Mockup for admin irc clients page:

![admin_irc_nicks](https://cloud.githubusercontent.com/assets/231684/3623143/b0363d96-0e47-11e4-8bb4-d504bccc87ed.png)

https://gist.github.com/rtnpro/196b540cf822103c533d

**Comment by rtnpro** [comment]
We can use http://startbootstrap.com/templates/sb-admin/index.html for admin interface

**Comment by rtnpro** [comment]
@sayanchowdhury @D-Ne0 comment
