### ISSUE TITLE
Why no issue for this milestone?

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#132]
Hey @D-Ne0 ,

IIRC, we'd agreed that you'd be creating issues for each task you'll be doing on a daily basis (or a few days), and marking the issues as fixed after committing your changes. Why are you not following this. Mailing updates is not a replacement for issue based workflow.

Let me know if you have any doubt.

**Comment by D-Ne0** [comment]
Sorry, I created issue at wrong place: https://github.com/waartaa/waartaa/issues/126
