### ISSUE TITLE
Messages sent by user is not saved to ElasticSearch

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#134]
@D-Ne0 

Currently, messages sent by user are not saved to ElasticSearch. We only save channel logs received by a node-irc client. However, the user who has sent a channel message never receives the message from the IRC server.

You remember the logic I use to handle this case? The `not_for_user` field during logging incoming message, and `global: false` when sending user message.

Fix it and push your changes.

**Comment by D-Ne0** [comment]
@rtnpro Unable to reproduce the issue. Let me know if you have any update on this issue
