### ISSUE TITLE
Change channel on mobile browser?

### ISSUE THREAD

**Issue by cjb** [waartaa/waartaa#136]
Hi, I tried logging into (self-hosted) waartaa from my Android phone, which has a 1920x1080 screen, but there doesn't seem to be any way to change channels, any ideas?  Thanks!

![image](https://cloud.githubusercontent.com/assets/21217/3489978/2170ea78-0552-11e4-8f75-37a3dd0edf7f.png)

**Comment by rtnpro** [comment]
@cjb the mobile interface does not yet work with Waartaa. What you see now in the mobile UI is the result of our initial experimentation with responsive design and it's terrible :(. However, we have resumed to work on making Waartaa render properly on mobile UI. Here are some initial mockups: https://github.com/waartaa/waartaa/issues/137. Please feel free to share your comments and feedback on the mockups. I believe that we should be able to get the mobile interface working by this month end.

**Comment by cjb** [comment]
@rtnpro Cool, thanks for the answer.  The mockups look great!  (If there's a simple fix to get channel switching working with mobile, even if it looks ugly for now, that'd be awesome.)

**Comment by rtnpro** [comment]
@cjb , it'd not be that difficult to have a basic implementation of channels/users list drawer using Twitter bootstrap. I will implement it ASAP to make the mobile interface functional :)

**Comment by rtnpro** [comment]
@cjb I just pushed an initial set of changes to make Waartaa usable from mobile. Please give it a shot and let me know how's it for a start?

**Comment by cjb** [comment]
@rtnpro Just gave it a quick try, it looks great, thanks so much!  Really impressed by Waartaa and your work on it.  :-)

**Comment by rtnpro** [comment]
@cjb Thanks for giving us the push to do it :+1:
