### ISSUE TITLE
First submission to connect to server fails to generate any visible server tab.

### ISSUE THREAD

**Issue by darkowlzz** [waartaa/waartaa#14]
When there are no connected servers and first server details are submitted, no server tab appears on the Server sidebar but terminal shows that the server tries to connect to the requested server.

On second submission, a server tab appears.

**Comment by darkowlzz** [comment]
I don't see how #16 solves this problem. That PR adds a line to install irc module, but this issue is about a front end bug.
When you connect to a irc network for the first time, the server tab doesn't show up on the left server side bar.

**Comment by kaushikgandhi** [comment]
wrong read my mistake .

**Comment by rtnpro** [comment]
@darkowlzz @kaushikgandhi Can it still be reproduced? I am not able to reproduce it at my end.

**Comment by kaushikgandhi** [comment]
@rtnpro But it seems problems persists . I tried reproducing it and i got the below screens

I was trying to connect to freenode when no previous servers were connected . 

![screenshot from 2014-05-15 15 45 18](https://cloud.githubusercontent.com/assets/2167564/2982816/045ad63a-dc1a-11e3-92f2-cc9cdffd0f55.png)

And i got a blank screen like this 

![screenshot from 2014-05-15 15 45 24](https://cloud.githubusercontent.com/assets/2167564/2982824/308f861a-dc1a-11e3-99b8-709807aaa270.png)
