### ISSUE TITLE
Unread message count should survive browser refresh

### ISSUE THREAD

**Issue by cjb** [waartaa/waartaa#151]
It feels strange that the count of unread messages per channel disappears when I reload my browser.  Reloading my browser doesn't signify that I've read everything.  Clicking on a channel signifies that I've probably read everything -- that would feel like a good time to mark the channel as no longer containing unread messages.  What do you think?  Thanks!

**Comment by sayanchowdhury** [comment]
True, the count of the number unread messages per channel should stay until you have visited the channel. Will look into the issue.

**Comment by rtnpro** [comment]
@cjb Yes, the current workflow is not proper. We'll be moving the functionality to track unread logs/mentions count to the server side. This will help us to keep these counts in sync across all user devices.

Thanks for reporting this issue :+1:

**Comment by rtnpro** [comment]
I had already created an issue for this https://github.com/waartaa/waartaa/issues/148 :)

**Comment by cjb** [comment]
Oh!  Okay, closing this one as duplicate of #148.  : )

**Comment by rtnpro** [comment]
@cjb We've finally moved tracking unread logs count and unread mentions count to the server side. Now, these stats persist across browser reloads and across multiple devices.

It was quite some challenge to move these computations on the server side retaining less complexity. However, we managed to do so.

We have deployed our devel codebase to try.waartaa.com. Please give it a shot :)
