### ISSUE TITLE
Scrolling the Users all the way to the bottom blocks the scrolling back up to the top

### ISSUE THREAD

**Issue by sudheesh001** [waartaa/waartaa#152]
I've noticed a few things, the Users are being `loaded` on every scroll to the bottom, but once i've scrolled all the way to the bottom of the users (Alphabetically sorted) I am unable to scroll back to the top.

Tested on :  Mozilla#gaia

**Comment by rtnpro** [comment]
@sudheesh001 Thanks for reporting this issue :+1: We are aware of this bug and have already created an issue: https://github.com/waartaa/waartaa/issues/105 tagged as `EasyFix` for any interested contributor :) Looks like that I have to fix it myself :\

**Comment by sudheesh001** [comment]
@rtnpro Maybe you should provide a description in #105 about how to fix the bug or the path of files to look at. :+1: Maybe that'll get them started.

**Comment by rtnpro** [comment]
Thanks @sudheesh001 :+1:
