### ISSUE TITLE
Enhance the color to #FFF for the fields on the right hand side of header

### ISSUE THREAD

**Issue by sudheesh001** [waartaa/waartaa#153]
![screen shot 2014-08-02 at 9 28 25 am](https://cloud.githubusercontent.com/assets/4545925/3787047/5448c11c-19f9-11e4-8b31-096151cfcef2.png)
should look like this, it looks better on the UI
![screen shot 2014-08-02 at 9 30 39 am](https://cloud.githubusercontent.com/assets/4545925/3787049/6e0a7aa0-19f9-11e4-8aa9-ce9c59971a43.png)

**Comment by rtnpro** [comment]
Yes, good point :+1: I will fix it :)
