### ISSUE TITLE
Minor errors and workarounds for deploy from head.

### ISSUE THREAD

**Issue by jayunit100** [waartaa/waartaa#156]
Ive found multiple errors deploying from head.

0) I had to manually chmod  -R the waarta/ package after running setup.sh. not sure why but i got an ENOENT error that my user couldnt chown a directory.

1)  I have to run  `mrt add kadira` or else I get a "no package kadira  " found error.

2) After that, when running meteor, I get a few non trivial errors:

```
error: circular dependency between packages blaze-layout and iron-router
error: circular dependency between packages blaze-layout and iron-layout
```

And the workaround is to start the app, and then run `meteor remove blaze-layout`.

After that point, it all works. :)  ill close the other two issues i opened since they are summarized here.

**Comment by rtnpro** [comment]
Thanks for reporting the issues :+1: We'll do the needful fixes ASAP.

**Comment by jayunit100** [comment]
looks like `mrt update` is also needed im crafting a pull request for updated README
