### ISSUE TITLE
No meaningfull message when connectivity to  server is down

### ISSUE THREAD

**Issue by jayunit100** [waartaa/waartaa#157]
When there is no network connectivity, a irc server just has an "X" next to it.  This is pretty touch go debug.    

In my case, I was triny to use WAARTA inside my VPN , and didnt realize that i was off of it.

Maybe a connection error would be nice to have?  

If somebody wants to outline the architecture of the app to me (im new to fancy js frameworks,,, but otherwise reasonably comptent :)), id be glad to add a patch for this.

**Comment by rtnpro** [comment]
Hi @jayunit100,

Thanks for taking a look at Waartaa and sharing your feedback :+1:

You'd like to take a look here https://github.com/waartaa/waartaa/blob/devel/app/server/lib/02_irc.js#L1498. May be we can handle the connection errors/timeout and set proper status to the `UserServer` and it'd automatically reflect in the client side.

Let me know if you need more info :)
