### ISSUE TITLE
Adblock Plus doesn't allow wãrtã to work on Firefox and Chrome.

### ISSUE THREAD

**Issue by darkowlzz** [waartaa/waartaa#17]
![screen shot 2013-12-28 at 9 55 05 am](https://f.cloud.github.com/assets/614105/1817156/00e9c032-6f79-11e3-8dcc-302539b1b7a0.png)
With Adblock Plus enabled, wãrtã fails to render on browser.

**Comment by kaushikgandhi** [comment]
![doesn t block](https://f.cloud.github.com/assets/2167564/1823830/53423bf0-7188-11e3-81ff-96fe859eafd9.png)
It doesn't block you should check your adblock settings .

**Comment by rtnpro** [comment]
Any update on this? Is this issue still persistent?

**Comment by debjeetsarkar** [comment]
When adblock is disabled on localhost , it works fine.

**Comment by ashishmverma1** [comment]
No issue here. I'm also running Waartaa on localhost, and its running fine with AdBlockP running (using Chrome browser)

**Comment by jaquer** [comment]
I can confirm this. It happens when one of the Adblock privacy lists is being used (in my case EasyPrivacy) and it prevents the loading of packages/GAnalytics.js.

The entire app stops working at that point.

I can provide more information if needed.

**Comment by rtnpro** [comment]
@jaquer 

I am sorry for dropping the ball on this. It'd be great if you could send a screenshot of any console error that you see in this case :)

@sayanchowdhury Please have a look in this ASAP.

**Comment by rtnpro** [comment]
I found no issue with adblockplus on try.waartaa.com. Closing this bug as fixed for now.
