### ISSUE TITLE
Don't autofocus chat input on chatroom selection for small screens

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#179]
Currently, the chat input box in a chatroom gets focused automatically, when the chatroom is selected. This behaviour is fine for larger screen sizes on desktops, laptops, but not on mobile devices where the soft keyboard shows up and causes unnecessary distraction.

The plan is to fire the autofocus the chat input box only for large screen sizes and above.

**Comment by sheeshmohsin** [comment]
I am willing to work on this. Please guide me.

**Comment by rtnpro** [comment]
@sheeshmohsin Thanks for your interest to work on this bug.

I will try to outline what I have in mind to fix this issue:
1. Install media-query package: `meteor add ficshelf:media-query`. This exposes Session variables for the current screen size.
2. We need to do a check before executing this line: https://github.com/waartaa/waartaa/blob/devel/app/client/chat/_lib/helpers.js#L33.

```
if (_.indexOf(['large', 'xlarge', 'xxlarge'], Session.get('screensize')) >= 0)
    $('#chat-input').focus();
```

I hope that this helps. Let me know if you have any question.

**Comment by rtnpro** [comment]
@sheeshmohsin Also, you could have a look at https://atmospherejs.com/mystor/device-detection instead of ficshelf:media-query.

**Comment by rtnpro** [comment]
Fixed.
