### ISSUE TITLE
PM by someone else disconnects the user

### ISSUE THREAD

**Issue by darkowlzz** [waartaa/waartaa#18]
When another user tries to PM me, I get disconnected.

**Comment by rtnpro** [comment]
Did you get any error log when it happened?

**Comment by darkowlzz** [comment]
Yea, here is a gist of the error log

https://gist.github.com/darkowlzz/8156604

**Comment by kaushikgandhi** [comment]
yeah i faced a similar error .

**Comment by rtnpro** [comment]
Fixed!
