### ISSUE TITLE
Clicking on a nick in chat log/channel nicks should autofill nick in chat input box

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#181]
Currently, for non desktop devices, it's difficult to press TAB to trigger nick auto completion. In most cases, the user would want to have conversation with the recently active nick or anyone from the channel's nick list. We need to make the nick clickable in channel chat log and channel nicks list, so that it can autofil the selected nick in the chat input box.

**Comment by rtnpro** [comment]
@sheeshmohsin wanna work on it?

**Comment by sheeshmohsin** [comment]
yes, sure :)

**Comment by rtnpro** [comment]
@sheeshmohsin Did you get the issue? Let me know if you have any question.

**Comment by sheeshmohsin** [comment]
When a user clicks on the nick, chat input box automatically fills the nick, is it?

**Comment by rtnpro** [comment]
Yes. The autofill is gonna be a bit tricky. You need to add proper space before and after the nick. I am thinking of the following rules:
1. If there's no existing text in the chat input box, autofill `<nick name>,`
2. If there's some existing text in the chat input box, autofill `<nick name>,`

Notice that while 2 starts with a space, 1 does not.

**Comment by sheeshmohsin** [comment]
and also in 2 comma (,) should not be included

**Comment by sheeshmohsin** [comment]
@rtnpro give me descriptions of the files, where the source code for the same is?

**Comment by rtnpro** [comment]
Let's include comma in both the cases after the nick. I will fix my existing nick autocompletion logic to include comma as well.

**Comment by rtnpro** [comment]
For chat log messages:
1. https://github.com/waartaa/waartaa/blob/devel/app/client/chat/chat_logs/chat_log_rows.html
2. https://github.com/waartaa/waartaa/blob/devel/app/client/chat/chat_logs/chat_log_rows.js

And for channel nicks list:
1. https://github.com/waartaa/waartaa/blob/devel/app/client/chat/info_panel/channel_nick.html
2. https://github.com/waartaa/waartaa/blob/devel/app/client/chat/info_panel/channel_nick.js
