### ISSUE TITLE
Autocomplete is currently case sensitive

### ISSUE THREAD

**Issue by sarupbanskota** [waartaa/waartaa#188]
Hi everyone,

I was trying to autocomplete "Emichan", but I normally would just do a "emi" and hit tab. Since it's case sensitive on Waartaa, it won't recognize. Thought it would be worthy of fix. 

Could you please point me to where to go about fixing it, I'll take it up?

Thanks!

**Comment by rtnpro** [comment]
@sarupbanskota Thanks for reporting this bug :+1: 

All you need to do is a case insensitive mongodb regex query here: https://github.com/waartaa/waartaa/blob/devel/app/server/publish.js#L312

Here's how to do it: http://stackoverflow.com/questions/1863399/mongodb-is-it-possible-to-make-a-case-insensitive-query

Please let me know if you have any question.

**Comment by jee1mr** [comment]
@rtnpro Hey, can I take this up?

**Comment by sarupbanskota** [comment]
Oh no I completely forgot about this. @jee1mr, please do.

**Comment by jee1mr** [comment]
@sarupbanskota Thanks :D

**Comment by jee1mr** [comment]
@rtnpro Made a PR. 
https://github.com/waartaa/waartaa/pull/197/
Please review and suggest changes if any.
