### ISSUE TITLE
Try waartaa ABUSED !!!

### ISSUE THREAD

**Issue by firemanxbr** [waartaa/waartaa#198]
I used one time, to test the project, but even offline try.waartaa.com of the service is trying to log in with my user on FreeNode, my user is: firemanxbr, before reporting the FreeNode asking here, please clean my informations.

**Comment by rtnpro** [comment]
Hi @firemanxbr 

There are some issues with the service as of now. I will clean up user: firemanxbr from the instance. We are in process of re writing Waartaa. Please stay tuned for updates.

**Comment by rtnpro** [comment]
Done!

**Comment by firemanxbr** [comment]
@rtnpro, thnkz for attention.
