### ISSUE TITLE
For few channels, can't see whats being typed

### ISSUE THREAD

**Issue by p00j4** [waartaa/waartaa#199]
in selenium channel, I'm not able to see what I have typed, nor seeing other's chat.
looks like read/write size limit is reached.

![image](https://cloud.githubusercontent.com/assets/6470509/7159077/3b726774-e39d-11e4-9d91-2dc3179e7400.png)

**Comment by rtnpro** [comment]
@p00j4 which channels are you on? Please try disconnecting/reconnecting to Freenode and then joining the channels.
