### ISSUE TITLE
Connect to other IRC server.

### ISSUE THREAD

**Issue by rajatjpatel** [waartaa/waartaa#200]
Hey Rtnpro,

1st of all thank you so much for "Waartaa" .

We have our internal IRC server which work on our school network. Using "Waartaa" we would like give web access to our student /teacher.

Following is our setup.

OS:- Fedora 22
IRC Server :-  ircd-ratbox-2.2.8
Domain :- school-internal-local
###### 

We have change following as our IRC server. @ /home/school/waartaa/app/server/settings-local.js

app/server/settings-local.js-dist:  'Freenode': {
app/server/settings-local.js-dist:      {url: 'irc.freenode.net', port: '6667'},
app/server/settings-local.js-dist:      {url: 'irc.freenode.net', port: '8000'}
app/lib/models/chat.js:  connections: List of items like {url: 'irc.freenode.net', port: '6667'}
app/lib/models/chat.js:  host: 'gateway/web/freenode/ip.123.201.128.134',
app/lib/models/chat.js:  realname: '123.201.128.134 - http://webchat.freenode.net',
app/lib/models/chat.js:  server: 'herbert.freenode.net',
mockups/html/index.html:                Freenode
mockups/html/index.html:                  <a href="#">You were mentioned in Freenode#dgplug 3 hours ago</a>
mockups/html/index.html:                  <a href="#">Sayan sent you a private message in Freenode 1 hour ago</a>
README.md:1. IRC: **#waartaa** on Freenode
provisions/roles/app_deploy/templates/settings_local.js.j2:  'Freenode': {
provisions/roles/app_deploy/templates/settings_local.js.j2:      {url: 'irc.freenode.net', port: '6697'},
provisions/roles/app_deploy/templates/settings_local.js.j2:      {url: 'irc.freenode.net', port: '8000'}
###### 

In place of freenode.net <school-internal-local> and Ip address
###### 

$ meteor 
[[[[[ ~/waartaa/app ]]]]]                     

=> Started proxy.  
=> Meteor 1.1.0.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.  
=> Errors prevented startup:                  

   While building the application:
   server/settings-local.js:8:1: Unexpected token ILLEGAL

=> Your application has errors. Waiting for file change.

We have try other open source tool like same it call subway. Which is work well but only this is if we have to create our internal group which don't work.

Can you help us to fix the same
Regards
R

**Comment by rtnpro** [comment]
Hey @rajatjpatel,

Thanks for your interest in Waartaa. Could you please paste your `settings-local.js` removing any private info, if any. It seems that there's a JS syntax error in line no. 8.

Also, we are working on rewriting Waartaa to make it more scalable and resilient. We're moving away from MeteorJS. However, this will take some time.

If you are in a hurry, why don't you try: https://github.com/erming/shout ?

**Comment by rajatjpatel** [comment]
thank you so much bro u r realy fast reply shout is working very well/...

Hi

Regards,
Rajat Patel

http://studyhat.blogspot.com
FIRST THEY IGNORE YOU...
THEN THEY LAUGH AT YOU...
THEN THEY FIGHT YOU...
THEN YOU WIN...

On Mon, Jun 29, 2015 at 1:19 PM, Ratnadeep Debnath <notifications@github.com
