### ISSUE TITLE
Able to access Meteor user id in client local storage

### ISSUE THREAD

**Issue by sheeshmohsin** [waartaa/waartaa#202]
![screenshot from 2015-06-27 18 30 04](https://cloud.githubusercontent.com/assets/4139932/8395609/cfa5c6cc-1d98-11e5-8b81-e7f96d1f572d.png)

Isn't its vulnerable or a security issue?

**Comment by rtnpro** [comment]
You can see only your user id, not others' user id. So, I do not see any issue here.
