### ISSUE TITLE
/me command

### ISSUE THREAD

**Issue by Pablo2m** [waartaa/waartaa#29]
The command /me not working

**Comment by rtnpro** [comment]
@Pablo2m Yes, it's not working now. It's in my TODO list. I will implement this by this weekend :)

Thanks for the request.

**Comment by rtnpro** [comment]
@Pablo2m Implemented support for `/me` command here 495b3fd71c4eaa8e039951641c97baadca1d90cc. Thanks for the request :+1:

**Comment by Pablo2m** [comment]
Thanks!

**Comment by Pablo2m** [comment]
Hello 
I was watching the /me pass unnoticed sometimes

![waartaa - mozilla firefox 31012014 081827 a m](https://f.cloud.github.com/assets/557413/2049940/2e79ee1c-8a6a-11e3-8788-e2e4d8ca7e98.jpg)

Does it ever change? thought something like this
![waartaa best - mozilla firefox 31012014 081827 a m](https://f.cloud.github.com/assets/557413/2049938/2d89711c-8a6a-11e3-97d6-7d7699122156.jpg)
