### ISSUE TITLE
nick doesn't changes if someone changes his nick

### ISSUE THREAD

**Issue by iamsudip** [waartaa/waartaa#34]
If someone join IRC using 'foo' nick(using different IRC client, say hexchat), waartaa says foo joined the channel.
But now, if 'foo' changes his nick to 'bar' using his IRC client(/nick bar), the right column still shows the nick as foo. So here comes the problem that there is no nick as 'foo' at present but waartaa shows there is a nick 'foo' and there is a nick 'bar' at present but waartaa do not shows 'bar'.

See this image: Here is a nick paidn0de(After changing the nick from iamsudip)
![untitled1](https://f.cloud.github.com/assets/4931226/2002509/a01cab9c-85f9-11e3-970c-1652edf4189d.jpg)

But waartaa do not show the update:(It still shows my previous nick)
![untitled](https://f.cloud.github.com/assets/4931226/2002513/ed5b09da-85f9-11e3-9f3d-27ebbc4d372d.jpg)

**Comment by rtnpro** [comment]
@iamsudip 

Thanks for the bug report. I have fixed it at 6d74b0a107704eeee9424fd8893d522ea122f7b9
