### ISSUE TITLE
Implement nick autocomplete via AJAX

### ISSUE THREAD

**Issue by rtnpro** [waartaa/waartaa#7]
Something similar to http://jqueryui.com/resources/demos/autocomplete/remote-jsonp.html can be used. A router needs to be added in the server code for this which will return the list of matching nicks.

**Comment by rtnpro** [comment]
Currently we have only a few ChannelNicks (currently 40 at max) for a channel available on client side. So, when the user tries to autocomplete a nick, we can first try to load matching nicks from local ChannelNicks to show some suggestion immediately. At the same time, we can fire an AJAX request to the server for other matching nicks and update the suggestions as soon as we get response from the server.

**Comment by rtnpro** [comment]
Steps to solve it:
1. Add an server side endpoint, say `/suggest/channelnicks/?server=<server_name>&channel=<channel_name>&pattern=<initial nick chars>` which would return a JSON list of matching nicks of max length N (configurable).
2. Update autocomplete source from AJAX response: https://github.com/waartaa/waartaa/blob/master/waartaa/client/chat.js#L282.

Here's an example how to do it: http://jqueryui.com/resources/demos/autocomplete/remote-jsonp.html

**Comment by kaushikgandhi** [comment]
Trying to solve this .

**Comment by rtnpro** [comment]
Fixed by @kaushikgandhi
